version: "3.8"

services:
  upreso-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upreso
    ports:
      - "8000:8000"
    command: ./main
    restart: unless-stopped
